server {
    listen 80;
    server_name localhost;

    location /NexusFrontEnd {
        alias /usr/share/nginx/html/NexusFrontEnd;
        # Esta línea es la magia: redirige todas las rutas internas a index.html
        try_files $uri $uri/ /NexusFrontEnd/index.html;
    }

    # Opcional: Redirigir la raíz (localhost) directamente a la app
    location / {
        rewrite ^/$ /NexusFrontEnd/ redirect;
    }
}