spring.application.name=NexusGatewayMs
server.port=8080
server.servlet.context-path=/NexusGateway

# =========================================================
# RUTA 1: Seguridad
# =========================================================
spring.cloud.gateway.server.webmvc.routes[0].id=seguridad-route
spring.cloud.gateway.server.webmvc.routes[0].uri=${URI_SEGURIDAD:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/seguridad/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=2
spring.cloud.gateway.server.webmvc.routes[0].filters[1]=PrefixPath=/NexusMS

# =========================================================
# RUTA 2: Catalogo
# =========================================================
spring.cloud.gateway.server.webmvc.routes[1].id=catalogo-route
spring.cloud.gateway.server.webmvc.routes[1].uri=${URI_CATALOGO:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/catalogo/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=2
spring.cloud.gateway.server.webmvc.routes[1].filters[1]=PrefixPath=/NexusMS

# =========================================================
# RUTA 3: Ingresos
# =========================================================
spring.cloud.gateway.server.webmvc.routes[2].id=ingresos-route
spring.cloud.gateway.server.webmvc.routes[2].uri=${URI_INGRESOS:http://localhost:8083}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/ingresos/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=2
spring.cloud.gateway.server.webmvc.routes[2].filters[1]=PrefixPath=/NexusMS

management.endpoints.web.exposure.include=health,info