spring.application.name=NexusCatalogoMs

# Puerto dedicado para aislar este microservicio del resto del ecosistema.
server.port=8082

# Context path global del microservicio. Spring Boot lo antepone a todas las rutas REST.
server.servlet.context-path=/NexusMS

# Configuracion de la conexion hacia la base de datos exclusiva del catalogo.
spring.datasource.url=jdbc:postgresql://localhost:5434/db_catalogo
spring.datasource.username=${DB_CATALOGO_USERNAME:admin_nexus}
spring.datasource.password=${DB_CATALOGO_PASSWORD:admin_password_123}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate no debe alterar el esquema
spring.jpa.hibernate.ddl-auto=none

# Estas propiedades ayudan a observar las consultas generadas por JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Evita mantener la sesion abierta durante la vista y obliga a resolver los datos en la capa de servicio.
spring.jpa.open-in-view=false
