spring.application.name=NexusSeguridadMs

# Puerto dedicado para aislar este microservicio del resto del ecosistema.
server.port=8081

# Context path global del microservicio. Spring Boot lo antepone a todas las rutas REST.
server.servlet.context-path=/NexusMS

# Configuracion de la conexion hacia la base de datos exclusiva de seguridad.
spring.datasource.url=jdbc:postgresql://localhost:5433/db_usuarios
spring.datasource.username=${DB_SEGURIDAD_USERNAME:admin_nexus}
spring.datasource.password=${DB_SEGURIDAD_PASSWORD:admin_password_123}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate no debe alterar el esquema en un entorno  si la base ya existe.
spring.jpa.hibernate.ddl-auto=none

# Estas propiedades ayudan a observar las consultas generadas por JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Evita mantener la sesion abierta durante la vista y obliga a resolver los datos en la capa de servicio.
spring.jpa.open-in-view=false
